//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHPortal.MasterPages {
    
    
    public partial class InspectionReportMaster {
        
        /// <summary>
        /// divMainCriteria control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.Panel divMainCriteria;
        
        /// <summary>
        /// lstTestSeq control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NHPortal.Classes.WebControls.TestSequenceListBox lstTestSeq;
        
        /// <summary>
        /// lstModelYear control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NHPortal.Classes.WebControls.ModelYearListBox lstModelYear;
        
        /// <summary>
        /// lstVehicleType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NHPortal.Classes.WebControls.VehicleTypeListBox lstVehicleType;
        
        /// <summary>
        /// lstCounty control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NHPortal.Classes.WebControls.CountyListBox lstCounty;
        
        /// <summary>
        /// dateSelector control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::NHPortal.UserControls.DatePeriodSelector dateSelector;
        
        /// <summary>
        /// hidReportType control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.HiddenField hidReportType;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new NHPortal.MasterPages.ReportMaster Master {
            get {
                return ((NHPortal.MasterPages.ReportMaster)(base.Master));
            }
        }
    }
}
