//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace NHPortal {
    
    
    public partial class TriggerCommProtocol {
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new NHPortal.MasterPages.TriggerMaster Master {
            get {
                return ((NHPortal.MasterPages.TriggerMaster)(base.Master));
            }
        }
    }
}
